const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('widget', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  updateConfig: (patch) => ipcRenderer.invoke('config:update', patch),
  setSecret: (section, value) => ipcRenderer.invoke('secret:set', section, value),
  onConfigChanged: (fn) => ipcRenderer.on('config-changed', (_e, c) => fn(c)),
  onOpenSettings: (fn) => ipcRenderer.on('open-settings', () => fn()),
  reportHeight: (h) => ipcRenderer.send('window:content-height', h),
  fetchCalendar: (from, to) => ipcRenderer.invoke('calendar:fetch', from, to),
  gcal: {
    status: () => ipcRenderer.invoke('gcal:status'),
    importClient: () => ipcRenderer.invoke('gcal:import-client'),
    connect: () => ipcRenderer.invoke('gcal:connect'),
    disconnect: () => ipcRenderer.invoke('gcal:disconnect'),
    create: (input) => ipcRenderer.invoke('gcal:create', input),
    update: (id, input) => ipcRenderer.invoke('gcal:update', id, input),
    remove: (id) => ipcRenderer.invoke('gcal:delete', id),
  },
  chat: (text, context) => ipcRenderer.invoke('ai:chat', text, context),
  onChatDelta: (fn) => ipcRenderer.on('ai:delta', (_e, d) => fn(d)),
  onChatStatus: (fn) => ipcRenderer.on('ai:status', (_e, s) => fn(s)),
  aiStatus: () => ipcRenderer.invoke('ai:status'),
  aiPresets: () => ipcRenderer.invoke('ai:presets'),
  aiLogin: (provider) => ipcRenderer.invoke('ai:login', provider),
  aiLogout: (provider) => ipcRenderer.invoke('ai:logout', provider),
  resetChat: () => ipcRenderer.invoke('ai:reset'),
  abortChat: () => ipcRenderer.invoke('ai:abort'),
  weatherLocations: (force) => ipcRenderer.invoke('weather:locations', force),
  weatherNationwide: (force) => ipcRenderer.invoke('weather:nationwide', force),
  searchPlace: (q) => ipcRenderer.invoke('weather:search', q),
  openNationwide: () => ipcRenderer.invoke('weather:open-nationwide'),
  closeSelf: () => ipcRenderer.invoke('window:close-self'),
  memo: {
    get: (id) => ipcRenderer.invoke('memo:get', id),
    open: (id) => ipcRenderer.invoke('memo:open', id),
    create: (initial, openAfter) => ipcRenderer.invoke('memo:create', initial, openAfter),
    update: (id, patch) => ipcRenderer.invoke('memo:update', id, patch),
    remove: (id) => ipcRenderer.invoke('memo:delete', id),
    closeSelf: () => ipcRenderer.invoke('memo:close-self'),
    onChanged: (fn) => ipcRenderer.on('memos-changed', (_e, list) => fn(list)),
  },
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
});
