const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('widget', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  updateConfig: (patch) => ipcRenderer.invoke('config:update', patch),
  setSecret: (section, value) => ipcRenderer.invoke('secret:set', section, value),
  log: (event, detail) => ipcRenderer.send('log', event, detail),
  onConfigChanged: (fn) => ipcRenderer.on('config-changed', (_e, c) => fn(c)),
  onOpenSettings: (fn) => ipcRenderer.on('open-settings', () => fn()),
  reportHeight: (h) => ipcRenderer.send('window:content-height', h),
  fetchCalendar: (from, to) => ipcRenderer.invoke('calendar:fetch', from, to),
  gcal: {
    status: () => ipcRenderer.invoke('gcal:status'),
    importClient: () => ipcRenderer.invoke('gcal:import-client'),
    connect: () => ipcRenderer.invoke('gcal:connect'),
    disconnect: () => ipcRenderer.invoke('gcal:disconnect'),
    create: (input) => ipcRenderer.invoke('gcal:create', input),
    update: (id, input) => ipcRenderer.invoke('gcal:update', id, input),
    remove: (id) => ipcRenderer.invoke('gcal:delete', id),
  },
  chat: (text, context) => ipcRenderer.invoke('ai:chat', text, context),
  onChatDelta: (fn) => ipcRenderer.on('ai:delta', (_e, d) => fn(d)),
  onChatStatus: (fn) => ipcRenderer.on('ai:status', (_e, s) => fn(s)),
  aiStatus: () => ipcRenderer.invoke('ai:status'),
  aiPresets: () => ipcRenderer.invoke('ai:presets'),
  aiLogin: (provider) => ipcRenderer.invoke('ai:login', provider),
  aiLogout: (provider) => ipcRenderer.invoke('ai:logout', provider),
  resetChat: () => ipcRenderer.invoke('ai:reset'),
  chatHistory: () => ipcRenderer.invoke('ai:history'),
  abortChat: () => ipcRenderer.invoke('ai:abort'),
  weatherLocations: (force) => ipcRenderer.invoke('weather:locations', force),
  weatherNationwide: (force) => ipcRenderer.invoke('weather:nationwide', force),
  searchPlace: (q) => ipcRenderer.invoke('weather:search', q),
  locate: () => ipcRenderer.invoke('weather:locate'),
  resolveImage: (url) => ipcRenderer.invoke('image:resolve', url),
  weatherAir: () => ipcRenderer.invoke('weather:air'),
  weatherWarnings: () => ipcRenderer.invoke('weather:warnings'),
  weatherAirStatus: () => ipcRenderer.invoke('weather:air-status'),
  weatherAirRecheck: () => ipcRenderer.invoke('weather:air-recheck'),
  openNationwide: () => ipcRenderer.invoke('weather:open-nationwide'),
  closeSelf: () => ipcRenderer.invoke('window:close-self'),
  showWidget: () => ipcRenderer.invoke('window:show-widget'),
  memo: {
    get: (id) => ipcRenderer.invoke('memo:get', id),
    open: (id) => ipcRenderer.invoke('memo:open', id),
    create: (initial, openAfter) => ipcRenderer.invoke('memo:create', initial, openAfter),
    update: (id, patch) => ipcRenderer.invoke('memo:update', id, patch),
    remove: (id) => ipcRenderer.invoke('memo:delete', id),
    closeSelf: () => ipcRenderer.invoke('memo:close-self'),
    onChanged: (fn) => ipcRenderer.on('memos-changed', (_e, list) => fn(list)),
  },
  quick: {
    onOpen: (fn) => ipcRenderer.on('quick:open', () => fn()),
    hide: () => ipcRenderer.invoke('quick:hide'),
    toWidget: (kind, payload) => ipcRenderer.invoke('quick:to-widget', kind, payload),
    status: () => ipcRenderer.invoke('quick:status'),
    setHotkey: (key) => ipcRenderer.invoke('quick:set-hotkey', key),
    onAction: (fn) => ipcRenderer.on('quick:action', (_e, kind, payload) => fn(kind, payload)),
  },
  backup: {
    status: () => ipcRenderer.invoke('backup:status'),
    now: () => ipcRenderer.invoke('backup:now'),
    open: () => ipcRenderer.invoke('backup:open'),
    restore: () => ipcRenderer.invoke('backup:restore'),
    chooseExtra: () => ipcRenderer.invoke('backup:choose-extra'),
    clearExtra: () => ipcRenderer.invoke('backup:clear-extra'),
  },
  flex: {
    status: () => ipcRenderer.invoke('flex:status'),
    fetch: () => ipcRenderer.invoke('flex:fetch'),
    login: () => ipcRenderer.invoke('flex:login'),
    disconnect: () => ipcRenderer.invoke('flex:disconnect'),
    setEnabled: (on) => ipcRenderer.invoke('flex:set-enabled', on),
    onChanged: (fn) => ipcRenderer.on('flex-changed', (_e, w) => fn(w)),
  },
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onb: {
    state: () => ipcRenderer.invoke('onb:state'),
    save: (patch) => ipcRenderer.invoke('onb:save', patch),
    place: (displayId, corner) => ipcRenderer.invoke('onb:place', displayId, corner),
    showWidget: () => ipcRenderer.invoke('onb:show-widget'),
    weatherTest: (key) => ipcRenderer.invoke('onb:weather-test', key),
    finish: (skipped) => ipcRenderer.invoke('onb:finish', skipped),
    open: (step) => ipcRenderer.invoke('onb:open', step),
    onFinished: (fn) => ipcRenderer.on('onb-finished', (_e, left) => fn(left)),
  },
});
